### ISSUE TITLE
Failed to load the nippo package

### ISSUE THREAD

**Issue by 50Wliu** [pastak/nippo#4]
_From @ebds on June 3, 2015 16:9_

[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 0.205.0
**System**: JENNY
**Thrown From**: Atom Core

### Stack Trace

Failed to load the nippo package

```
At unexpected newline

[stdin]:2:10: error: unexpected newline
"menu": [
         ^
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Sites",
    "destroyEmptyPanes": false
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "tabLength": 4,
    "softWrapHangingIndent": 4
  }
}
```

### Installed Packages

```coffee
# User
git-log, v0.4.1
git-tab-status, v1.9.2
line-diff-details, v1.1.1
linter, v0.12.6
tree-view-git-projects, v0.5.0

# Dev
No dev packages
```

_Copied from original issue: atom/atom#7081_

**Comment by ebds** [comment]
Why is this invalid? Sorry for asking but I don't understand

**Comment by pastak** [comment]
@50Wliu @ebds Thank you for your report. 

I reproduce same issue on my Atom.  I'll fix it.

**Comment by pastak** [comment]
@ebds I updated 0.1.1 and fixed this issue
